apiVersion: v1
kind: Service
metadata:
  name: nbl-wordpress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: wordpress
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
